package eu.city4age.dashboard.api.model;

// default package
// Generated 24-Nov-2016 15:43:47 by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * Action generated by hbm2java
 */
public class Action extends AbstractBaseEntity {

	private String actionName;
	private String category;
	private Set eams = new HashSet(0);
	private Set executedActions = new HashSet(0);

	public Action() {
	}

	public Action(String actionName, String category, Set eams, Set executedActions) {
		this.actionName = actionName;
		this.category = category;
		this.eams = eams;
		this.executedActions = executedActions;
	}

	public String getActionName() {
		return this.actionName;
	}

	public void setActionName(String actionName) {
		this.actionName = actionName;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public Set getEams() {
		return this.eams;
	}

	public void setEams(Set eams) {
		this.eams = eams;
	}

	public Set getExecutedActions() {
		return this.executedActions;
	}

	public void setExecutedActions(Set executedActions) {
		this.executedActions = executedActions;
	}

}
