package eu.city4age.dashboard.api.model;

// default package
// Generated 24-Nov-2016 15:43:47 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Assessment generated by hbm2java
 */
public class Assessment extends AbstractBaseEntity {

	private UserInRole userInRole;
	private String assessmentComment;
	private Character riskStatus;
	private Character dataValidityStatus;
	private Date created;
	private Date updated;
	
	@JsonManagedReference
	private Set assessmentAudienceRoles = new HashSet(0);
	
	@JsonManagedReference
	private Set assessedGefValueSets = new HashSet(0);

	public Assessment() {
	}

	public Assessment(UserInRole userInRole, String assessmentComment, Character riskStatus,
			Character dataValidityStatus, Date created, Date updated, Set assessmentAudienceRoles, Set assessedGefValueSets) {
		this.userInRole = userInRole;
		this.assessmentComment = assessmentComment;
		this.riskStatus = riskStatus;
		this.dataValidityStatus = dataValidityStatus;
		this.created = created;
		this.updated = updated;
		this.assessmentAudienceRoles = assessmentAudienceRoles;
		this.assessedGefValueSets = assessedGefValueSets;
	}

	public UserInRole getUserInRole() {
		return this.userInRole;
	}

	public void setUserInRole(UserInRole userInRole) {
		this.userInRole = userInRole;
	}

	public String getAssessmentComment() {
		return this.assessmentComment;
	}

	public void setAssessmentComment(String assessmentComment) {
		this.assessmentComment = assessmentComment;
	}

	public Character getRiskStatus() {
		return this.riskStatus;
	}

	public void setRiskStatus(Character riskStatus) {
		this.riskStatus = riskStatus;
	}

	public Character getDataValidityStatus() {
		return this.dataValidityStatus;
	}

	public void setDataValidityStatus(Character dataValidityStatus) {
		this.dataValidityStatus = dataValidityStatus;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public Set getAssessmentAudienceRoles() {
		return this.assessmentAudienceRoles;
	}

	public void setAssessmentAudienceRoles(Set assessmentAudienceRoles) {
		this.assessmentAudienceRoles = assessmentAudienceRoles;
	}

	public Set getAssessedGefValueSets() {
		return assessedGefValueSets;
	}

	public void setAssessedGefValueSets(Set assessedGefValueSets) {
		this.assessedGefValueSets = assessedGefValueSets;
	}

}
