package eu.city4age.dashboard.api.model;

// default package
// Generated 24-Nov-2016 15:43:47 by Hibernate Tools 5.2.0.Beta1

/**
 * AssessedSet generated by hbm2java
 */
public class AssessedSet extends AbstractBaseEntity {

	private AssessedSetId assessedSetId;
	private Assessment assessment;
	private GeriatricFactorValue geriatricFactorValue;

	public AssessedSet() {
	}

	public AssessedSet(Assessment assessment, GeriatricFactorValue geriatricFactorValue) {
		this.assessment = assessment;
		this.geriatricFactorValue = geriatricFactorValue;
	}

	public AssessedSetId getAssessedSetId() {
		return assessedSetId;
	}

	public void setAssessedSetId(AssessedSetId assessedSetId) {
		this.assessedSetId = assessedSetId;
	}

	public Assessment getAssessment() {
		return this.assessment;
	}

	public void setAssessment(Assessment assessment) {
		this.assessment = assessment;
	}

	public GeriatricFactorValue getGeriatricFactorValue() {
		return geriatricFactorValue;
	}

	public void setGeriatricFactorValue(GeriatricFactorValue geriatricFactorValue) {
		this.geriatricFactorValue = geriatricFactorValue;
	}


}
