package eu.city4age.dashboard.api.model;

// default package
// Generated 24-Nov-2016 15:43:47 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.apache.log4j.Logger;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Assessment generated by hbm2java
 */
public class Assessment extends AbstractBaseEntity {
	
	static protected Logger logger = Logger.getLogger(Assessment.class);

	private UserInRole userInRole;
	private String assessmentComment;
	private Character riskStatus;
	private Character dataValidityStatus;
	
	@JsonManagedReference
	private GeriatricFactorValue geriatricFactorValue;
	
	private Set<CdRole> roles = new HashSet<CdRole>(0);
	
	@JsonIgnore
	private Date created;
	
	@JsonIgnore
	private Date updated;

	public Assessment() {	
	}

	public Assessment(UserInRole userInRole, String assessmentComment, Character riskStatus,
			Character dataValidityStatus, GeriatricFactorValue geriatricFactorValue,
			Date created, Date updated, Set<CdRole> roles) {
		this.userInRole = userInRole;
		this.assessmentComment = assessmentComment;
		this.riskStatus = riskStatus;
		this.dataValidityStatus = dataValidityStatus;
		this.created = created;
		this.updated = updated;
		this.geriatricFactorValue = geriatricFactorValue;
		this.roles = roles;
	}

	public UserInRole getUserInRole() {
		return this.userInRole;
	}

	public void setUserInRole(UserInRole userInRole) {
		this.userInRole = userInRole;
	}

	public String getAssessmentComment() {
		return this.assessmentComment;
	}

	public void setAssessmentComment(String assessmentComment) {
		this.assessmentComment = assessmentComment;
	}

	public Character getRiskStatus() {
		return this.riskStatus;
	}

	public void setRiskStatus(Character riskStatus) {
		this.riskStatus = riskStatus;
	}

	public Character getDataValidityStatus() {
		return this.dataValidityStatus;
	}

	public void setDataValidityStatus(Character dataValidityStatus) {
		this.dataValidityStatus = dataValidityStatus;
	}

	public GeriatricFactorValue getGeriatricFactorValue() {
		return geriatricFactorValue;
	}

	public void setGeriatricFactorValue(GeriatricFactorValue geriatricFactorValue) {
		this.geriatricFactorValue = geriatricFactorValue;
		logger.info("GEF: " + geriatricFactorValue);
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public Set<CdRole> getRoles() {
		return roles;
	}

	public void setRoles(Set<CdRole> roles) {
		this.roles = roles;
	}

	public Date getCreated() {
		return created;
	}

	public Date getUpdated() {
		return updated;
	}

}
