package eu.city4age.dashboard.api.model;

import java.io.Serializable;

// default package
// Generated 24-Nov-2016 15:43:47 by Hibernate Tools 5.2.0.Beta1

/**
 * SourceEvidenceId generated by hbm2java
 */
public class AssessmentAudienceRoleId implements Serializable {

	private int assessmentId;
	private int userInRoleId;

	public AssessmentAudienceRoleId() {
	}

	public AssessmentAudienceRoleId(int assessmentId, int userInRoleId) {
		this.assessmentId = assessmentId;
		this.userInRoleId = userInRoleId;
	}

	public int getAssessmentId() {
		return assessmentId;
	}

	public void setAssessmentId(int assessmentId) {
		this.assessmentId = assessmentId;
	}

	public int getUserInRoleId() {
		return userInRoleId;
	}

	public void setUserInRoleId(int userInRoleId) {
		this.userInRoleId = userInRoleId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SourceEvidenceId))
			return false;
		SourceEvidenceId castOther = (SourceEvidenceId) other;

		return (this.getAssessmentId() == castOther.getGeriatricFactorId())
				&& ((this.getUserInRoleId() == castOther.getUserInRoleId()));
	}
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAssessmentId();
		result = 37 * result + this.getUserInRoleId();
		return result;
	}

}
