package eu.city4age.dashboard.api.model;

import com.fasterxml.jackson.annotation.JsonBackReference;

// default package
// Generated 24-Nov-2016 15:43:47 by Hibernate Tools 5.2.0.Beta1

/**
 * AssessedGefValueSet generated by hbm2java
 */
public class AssessedGefValueSet implements java.io.Serializable {

	private AssessedGefValueSetId assessedGefValueSetId;

	@JsonBackReference
	private Assessment assessment;
	
	@JsonBackReference 
	private GeriatricFactorValue geriatricFactorValue;

	public AssessedGefValueSet() {
	}

	public AssessedGefValueSet(Assessment assessment, GeriatricFactorValue geriatricFactorValue) {
		this.assessment = assessment;
		this.geriatricFactorValue = geriatricFactorValue;
	}

	public AssessedGefValueSetId getAssessedGefValueSetId() {
		return assessedGefValueSetId;
	}

	public void setAssessedGefValueSetId(AssessedGefValueSetId assessedGefValueSetId) {
		this.assessedGefValueSetId = assessedGefValueSetId;
	}

	public Assessment getAssessment() {
		return this.assessment;
	}

	public void setAssessment(Assessment assessment) {
		this.assessment = assessment;
	}

	public GeriatricFactorValue getGeriatricFactorValue() {
		return geriatricFactorValue;
	}

	public void setGeriatricFactorValue(GeriatricFactorValue geriatricFactorValue) {
		this.geriatricFactorValue = geriatricFactorValue;
	}


}
