package eu.city4age.dashboard.api.model;

import java.io.Serializable;

// default package
// Generated 24-Nov-2016 15:43:47 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;

/**
 * CareProfile generated by hbm2java
 */
public class CareProfile implements Serializable {

	private int userInRoleId;
	private UserInRole userInRoleById;
	private UserInRole userInRoleByLastUpdatedBy;
	private UserInRole userInRoleByCreatedBy;
	private String individualSummary;
	private Character attentionStatus;
	private Character interventionStatus;
	private Date lastInterventionDate;
	private Date created;
	private Date lastUpdated;

	public CareProfile() {
	}

	public CareProfile(UserInRole userInRoleById, UserInRole userInRoleByCreatedBy, String individualSummary,
			Date created) {
		this.userInRoleById = userInRoleById;
		this.userInRoleByCreatedBy = userInRoleByCreatedBy;
		this.individualSummary = individualSummary;
		this.created = created;
	}

	public CareProfile(UserInRole userInRoleById, UserInRole userInRoleByLastUpdatedBy,
			UserInRole userInRoleByCreatedBy, String individualSummary, Character attentionStatus,
			Character interventionStatus, Date lastInterventionDate, Date created, Date lastUpdated) {
		this.userInRoleById = userInRoleById;
		this.userInRoleByLastUpdatedBy = userInRoleByLastUpdatedBy;
		this.userInRoleByCreatedBy = userInRoleByCreatedBy;
		this.individualSummary = individualSummary;
		this.attentionStatus = attentionStatus;
		this.interventionStatus = interventionStatus;
		this.lastInterventionDate = lastInterventionDate;
		this.created = created;
		this.lastUpdated = lastUpdated;
	}

	public int getUserInRoleId() {
		return this.userInRoleId;
	}

	public void setUserInRoleId(int userInRoleId) {
		this.userInRoleId = userInRoleId;
	}

	public UserInRole getUserInRoleById() {
		return this.userInRoleById;
	}

	public void setUserInRoleById(UserInRole userInRoleById) {
		this.userInRoleById = userInRoleById;
	}

	public UserInRole getUserInRoleByLastUpdatedBy() {
		return this.userInRoleByLastUpdatedBy;
	}

	public void setUserInRoleByLastUpdatedBy(UserInRole userInRoleByLastUpdatedBy) {
		this.userInRoleByLastUpdatedBy = userInRoleByLastUpdatedBy;
	}

	public UserInRole getUserInRoleByCreatedBy() {
		return this.userInRoleByCreatedBy;
	}

	public void setUserInRoleByCreatedBy(UserInRole userInRoleByCreatedBy) {
		this.userInRoleByCreatedBy = userInRoleByCreatedBy;
	}

	public String getIndividualSummary() {
		return this.individualSummary;
	}

	public void setIndividualSummary(String individualSummary) {
		this.individualSummary = individualSummary;
	}

	public Character getAttentionStatus() {
		return this.attentionStatus;
	}

	public void setAttentionStatus(Character attentionStatus) {
		this.attentionStatus = attentionStatus;
	}

	public Character getInterventionStatus() {
		return this.interventionStatus;
	}

	public void setInterventionStatus(Character interventionStatus) {
		this.interventionStatus = interventionStatus;
	}

	public Date getLastInterventionDate() {
		return this.lastInterventionDate;
	}

	public void setLastInterventionDate(Date lastInterventionDate) {
		this.lastInterventionDate = lastInterventionDate;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

}
