package eu.city4age.dashboard.api.model;

// default package
// Generated 24-Nov-2016 15:43:47 by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * CdDataSourceType generated by hbm2java
 */
public class CdDataSourceType extends AbstractBaseEntity {

	private String dataSourceType;
	private String dataSourceTypeDescription;
	private Set variationMeasureValues = new HashSet(0);
	private Set activities = new HashSet(0);
	private Set numericIndicatorValues = new HashSet(0);

	public CdDataSourceType() {
	}

	public CdDataSourceType(String dataSourceType, String dataSourceTypeDescription) {
		this.dataSourceType = dataSourceType;
		this.dataSourceTypeDescription = dataSourceTypeDescription;
	}

	public CdDataSourceType(String dataSourceType, String dataSourceTypeDescription, Set variationMeasureValues,
			Set activities, Set numericIndicatorValues) {
		this.dataSourceType = dataSourceType;
		this.dataSourceTypeDescription = dataSourceTypeDescription;
		this.variationMeasureValues = variationMeasureValues;
		this.activities = activities;
		this.numericIndicatorValues = numericIndicatorValues;
	}

	public String getDataSourceType() {
		return this.dataSourceType;
	}

	public void setDataSourceType(String dataSourceType) {
		this.dataSourceType = dataSourceType;
	}

	public String getDataSourceTypeDescription() {
		return this.dataSourceTypeDescription;
	}

	public void setDataSourceTypeDescription(String dataSourceTypeDescription) {
		this.dataSourceTypeDescription = dataSourceTypeDescription;
	}

	public Set getVariationMeasureValues() {
		return this.variationMeasureValues;
	}

	public void setVariationMeasureValues(Set variationMeasureValues) {
		this.variationMeasureValues = variationMeasureValues;
	}

	public Set getActivities() {
		return this.activities;
	}

	public void setActivities(Set activities) {
		this.activities = activities;
	}

	public Set getNumericIndicatorValues() {
		return this.numericIndicatorValues;
	}

	public void setNumericIndicatorValues(Set numericIndicatorValues) {
		this.numericIndicatorValues = numericIndicatorValues;
	}

}
