package eu.city4age.dashboard.api.model;

import java.math.BigDecimal;

// default package
// Generated 24-Nov-2016 15:43:47 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * CdDetectionVariable generated by hbm2java
 */
public class CdDetectionVariable extends AbstractBaseEntity {

	private String detectionVariableName;
	
	@JsonIgnore
	private Date validFrom;
	
	@JsonIgnore
	private Date validTo;
	
	private BigDecimal derivationWeight;

	private Set<CdPilotDetectionVariable> cdPilotDetectionVariables = new HashSet<CdPilotDetectionVariable>(0);

	@JsonIgnore
	private CdDetectionVariable derivedDetectionVariable;
	
	@JsonIgnore
	private  CdDetectionVariableType detectionVariableType;

	public CdDetectionVariable() {
	}

	public CdDetectionVariable(String detectionVariableName, CdDetectionVariableType detectionVariableType, Date validFrom,
			Date validTo, BigDecimal derivationWeight, Set<CdPilotDetectionVariable> cdPilotDetectionVariables,
			CdDetectionVariable derivedDetectionVariable) {
		this.detectionVariableName = detectionVariableName;
		this.detectionVariableType = detectionVariableType;
		this.validFrom = validFrom;
		this.validTo = validTo;
		this.cdPilotDetectionVariables = cdPilotDetectionVariables;
		this.derivedDetectionVariable = derivedDetectionVariable;
	}

	public String getDetectionVariableName() {
		return this.detectionVariableName;
	}

	public void setDetectionVariableName(String detectionVariableName) {
		this.detectionVariableName = detectionVariableName;
	}

	public CdDetectionVariableType getDetectionVariableType() {
		return detectionVariableType;
	}

	public void setDetectionVariableType(CdDetectionVariableType detectionVariableType) {
		this.detectionVariableType = detectionVariableType;
	}

	public void setValidFrom(Date validFrom) {
		this.validFrom = validFrom;
	}

	public void setValidTo(Date validTo) {
		this.validTo = validTo;
	}

	public CdDetectionVariable getDerivedDetectionVariable() {
		return derivedDetectionVariable;
	}

	public void setDerivedDetectionVariable(CdDetectionVariable derivedDetectionVariable) {
		this.derivedDetectionVariable = derivedDetectionVariable;
	}

	public Set<CdPilotDetectionVariable> getCdPilotDetectionVariables() {
		return this.cdPilotDetectionVariables;
	}

	public void setCdPilotDetectionVariables(Set<CdPilotDetectionVariable> cdPilotDetectionVariables) {
		this.cdPilotDetectionVariables = cdPilotDetectionVariables;
	}

	public BigDecimal getDerivationWeight() {
		return derivationWeight;
	}

	public void setDerivationWeight(BigDecimal derivationWeight) {
		this.derivationWeight = derivationWeight;
	}

	public Date getValidFrom() {
		return validFrom;
	}

	public Date getValidTo() {
		return validTo;
	}
	
}
