package eu.city4age.dashboard.api.model;

import java.math.BigDecimal;

// default package
// Generated 24-Nov-2016 15:43:47 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CdDetectionVariable generated by hbm2java
 */
public class CdDetectionVariable extends AbstractBaseEntity {

	private String detectionVariableName;
	private String detectionVariableType;
	private Date validFrom;
	private Date validTo;
	private Short parentId;
	
	private BigDecimal derivationWeight;
	
	private Set variationMeasureValues = new HashSet(0);
	private Set cdPilotDetectionVariables = new HashSet(0);
	private Set numericIndicatorValues = new HashSet(0);
	
	private Set<Pilot> pilots = new HashSet<Pilot>();

	public CdDetectionVariable() {
	}

	public CdDetectionVariable(String detectionVariableName, String detectionVariableType, Date validFrom,
			Date validTo, Short parentId, BigDecimal derivationWeight, Set variationMeasureValues, Set cdPilotDetectionVariables,
			Set numericIndicatorValues) {
		this.detectionVariableName = detectionVariableName;
		this.detectionVariableType = detectionVariableType;
		this.validFrom = validFrom;
		this.validTo = validTo;
		this.parentId = parentId;
		this.variationMeasureValues = variationMeasureValues;
		this.cdPilotDetectionVariables = cdPilotDetectionVariables;
		this.numericIndicatorValues = numericIndicatorValues;
	}

	public String getDetectionVariableName() {
		return this.detectionVariableName;
	}

	public void setDetectionVariableName(String detectionVariableName) {
		this.detectionVariableName = detectionVariableName;
	}

	public String getDetectionVariableType() {
		return this.detectionVariableType;
	}

	public void setDetectionVariableType(String detectionVariableType) {
		this.detectionVariableType = detectionVariableType;
	}

	public Date getValidFrom() {
		return this.validFrom;
	}

	public void setValidFrom(Date validFrom) {
		this.validFrom = validFrom;
	}

	public Date getValidTo() {
		return this.validTo;
	}

	public void setValidTo(Date validTo) {
		this.validTo = validTo;
	}

	public Short getParentId() {
		return this.parentId;
	}

	public void setParentId(Short parentId) {
		this.parentId = parentId;
	}

	public Set getVariationMeasureValues() {
		return this.variationMeasureValues;
	}

	public void setVariationMeasureValues(Set variationMeasureValues) {
		this.variationMeasureValues = variationMeasureValues;
	}

	public Set getCdPilotDetectionVariables() {
		return this.cdPilotDetectionVariables;
	}

	public void setCdPilotDetectionVariables(Set cdPilotDetectionVariables) {
		this.cdPilotDetectionVariables = cdPilotDetectionVariables;
	}

	public Set getNumericIndicatorValues() {
		return this.numericIndicatorValues;
	}

	public void setNumericIndicatorValues(Set numericIndicatorValues) {
		this.numericIndicatorValues = numericIndicatorValues;
	}

	public Set<Pilot> getPilots() {
		return pilots;
	}

	public void setPilots(Set<Pilot> pilots) {
		this.pilots = pilots;
	}

	public BigDecimal getDerivationWeight() {
		return derivationWeight;
	}

	public void setDerivationWeight(BigDecimal derivationWeight) {
		this.derivationWeight = derivationWeight;
	}
	
}
