package eu.city4age.dashboard.api.model;

// default package
// Generated 05-Dec-2016 15:33:07 by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * CdFrailtyStatus generated by hbm2java
 */
public class CdFrailtyStatus implements java.io.Serializable {

	private String frailtyStatus;
	private String frailtyStatusDescription;
	private Set frailtyStatusTimelines = new HashSet(0);

	public CdFrailtyStatus() {
	}

	public CdFrailtyStatus(String frailtyStatus) {
		this.frailtyStatus = frailtyStatus;
	}

	public CdFrailtyStatus(String frailtyStatus, String frailtyStatusDescription, Set frailtyStatusTimelines) {
		this.frailtyStatus = frailtyStatus;
		this.frailtyStatusDescription = frailtyStatusDescription;
		this.frailtyStatusTimelines = frailtyStatusTimelines;
	}

	public String getFrailtyStatus() {
		return this.frailtyStatus;
	}

	public void setFrailtyStatus(String frailtyStatus) {
		this.frailtyStatus = frailtyStatus;
	}

	public String getFrailtyStatusDescription() {
		return this.frailtyStatusDescription;
	}

	public void setFrailtyStatusDescription(String frailtyStatusDescription) {
		this.frailtyStatusDescription = frailtyStatusDescription;
	}

	public Set getFrailtyStatusTimelines() {
		return this.frailtyStatusTimelines;
	}

	public void setFrailtyStatusTimelines(Set frailtyStatusTimelines) {
		this.frailtyStatusTimelines = frailtyStatusTimelines;
	}

}
