package eu.city4age.dashboard.api.model;

import java.io.Serializable;

// default package
// Generated 24-Nov-2016 15:43:47 by Hibernate Tools 5.2.0.Beta1

/**
 * CdPilotDetectionVariableId generated by hbm2java
 */
public class CdPilotDetectionVariableId implements Serializable {

	private int pilotId;
	private short detectionVariableId;

	public CdPilotDetectionVariableId() {
	}

	public CdPilotDetectionVariableId(int pilotId, short detectionVariableId) {
		this.pilotId = pilotId;
		this.detectionVariableId = detectionVariableId;
	}

	public int getPilotId() {
		return this.pilotId;
	}

	public void setPilotId(int pilotId) {
		this.pilotId = pilotId;
	}

	public short getDetectionVariableId() {
		return this.detectionVariableId;
	}

	public void setDetectionVariableId(short detectionVariableId) {
		this.detectionVariableId = detectionVariableId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CdPilotDetectionVariableId))
			return false;
		CdPilotDetectionVariableId castOther = (CdPilotDetectionVariableId) other;

		return (this.getPilotId() == castOther.getPilotId())
				&& (this.getDetectionVariableId() == castOther.getDetectionVariableId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPilotId();
		result = 37 * result + this.getDetectionVariableId();
		return result;
	}

}
