package eu.city4age.dashboard.api.model;

// default package
// Generated 24-Nov-2016 15:43:47 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;

/**
 * CdTypicalPeriod generated by hbm2java
 */
public class CdTypicalPeriod extends AbstractBaseEntity {

	private String typicalPeriod;
	private String periodDescription;
	private Date typicalDuration;

	public CdTypicalPeriod() {
	}

	public CdTypicalPeriod(String typicalPeriod) {
		this.typicalPeriod = typicalPeriod;
	}

	public CdTypicalPeriod(String typicalPeriod, String periodDescription, Date typicalDuration) {
		this.typicalPeriod = typicalPeriod;
		this.periodDescription = periodDescription;
		this.typicalDuration = typicalDuration;
	}

	public String getTypicalPeriod() {
		return this.typicalPeriod;
	}

	public void setTypicalPeriod(String typicalPeriod) {
		this.typicalPeriod = typicalPeriod;
	}

	public String getPeriodDescription() {
		return this.periodDescription;
	}

	public void setPeriodDescription(String periodDescription) {
		this.periodDescription = periodDescription;
	}

	public Date getTypicalDuration() {
		return this.typicalDuration;
	}

	public void setTypicalDuration(Date typicalDuration) {
		this.typicalDuration = typicalDuration;
	}

}
