package eu.city4age.dashboard.api.model;

// default package
// Generated 24-Nov-2016 15:43:47 by Hibernate Tools 5.2.0.Beta1

import java.math.BigDecimal;
import java.util.Date;

/**
 * CrProfile generated by hbm2java
 */
public class CrProfile extends AbstractBaseEntity {

	private UserInRole userInRole;
	private Float refHeight;
	private Float refWeight;
	private BigDecimal refMeanBloodPressure;
	private Date date;
	private Date birthDate;
	private boolean gender;

	public CrProfile() {
	}

	public CrProfile(UserInRole userInRole, Date birthDate, boolean gender) {
		this.userInRole = userInRole;
		this.birthDate = birthDate;
		this.gender = gender;
	}

	public CrProfile(UserInRole userInRole, Float refHeight, Float refWeight, BigDecimal refMeanBloodPressure,
			Date date, Date birthDate, boolean gender) {
		this.userInRole = userInRole;
		this.refHeight = refHeight;
		this.refWeight = refWeight;
		this.refMeanBloodPressure = refMeanBloodPressure;
		this.date = date;
		this.birthDate = birthDate;
		this.gender = gender;
	}

	public UserInRole getUserInRole() {
		return this.userInRole;
	}

	public void setUserInRole(UserInRole userInRole) {
		this.userInRole = userInRole;
	}

	public Float getRefHeight() {
		return this.refHeight;
	}

	public void setRefHeight(Float refHeight) {
		this.refHeight = refHeight;
	}

	public Float getRefWeight() {
		return this.refWeight;
	}

	public void setRefWeight(Float refWeight) {
		this.refWeight = refWeight;
	}

	public BigDecimal getRefMeanBloodPressure() {
		return this.refMeanBloodPressure;
	}

	public void setRefMeanBloodPressure(BigDecimal refMeanBloodPressure) {
		this.refMeanBloodPressure = refMeanBloodPressure;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	public boolean isGender() {
		return this.gender;
	}

	public void setGender(boolean gender) {
		this.gender = gender;
	}

}
