package eu.city4age.dashboard.api.model;

// default package
// Generated 24-Nov-2016 15:43:47 by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * Eam generated by hbm2java
 */
public class Eam extends AbstractBaseEntity {

	private Action action;
	private Activity activity;
	private Integer duration;
	private Set startranges = new HashSet(0);
	private Set simplelocations = new HashSet(0);

	public Eam() {
	}

	public Eam(Action action, Activity activity) {
		this.action = action;
		this.activity = activity;
	}

	public Eam(Action action, Activity activity, Integer duration, Set startranges, Set simplelocations) {
		this.action = action;
		this.activity = activity;
		this.duration = duration;
		this.startranges = startranges;
		this.simplelocations = simplelocations;
	}

	public Action getAction() {
		return this.action;
	}

	public void setAction(Action action) {
		this.action = action;
	}

	public Activity getActivity() {
		return this.activity;
	}

	public void setActivity(Activity activity) {
		this.activity = activity;
	}

	public Integer getDuration() {
		return this.duration;
	}

	public void setDuration(Integer duration) {
		this.duration = duration;
	}

	public Set getStartranges() {
		return this.startranges;
	}

	public void setStartranges(Set startranges) {
		this.startranges = startranges;
	}

	public Set getSimplelocations() {
		return this.simplelocations;
	}

	public void setSimplelocations(Set simplelocations) {
		this.simplelocations = simplelocations;
	}

}
