package eu.city4age.dashboard.api.model;

// default package
// Generated 24-Nov-2016 15:43:47 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;

/**
 * FrailtyStatusTimelineId generated by hbm2java
 */
public class FrailtyStatusTimelineId implements java.io.Serializable {

	private long timeIntervalId;
	private long changedById;

	public FrailtyStatusTimelineId() {
	}

	public FrailtyStatusTimelineId(long timeIntervalId, long changedById) {
		this.timeIntervalId = timeIntervalId;
		this.changedById = changedById;
	}

	public long getTimeIntervalId() {
		return this.timeIntervalId;
	}

	public void setTimeIntervalId(long timeIntervalId) {
		this.timeIntervalId = timeIntervalId;
	}
	
	public long getChangedById() {
		return changedById;
	}

	public void setChangedById(long changedById) {
		this.changedById = changedById;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FrailtyStatusTimelineId))
			return false;
		FrailtyStatusTimelineId castOther = (FrailtyStatusTimelineId) other;

		return (this.getTimeIntervalId() == castOther.getTimeIntervalId())
				&& ((this.getChangedById() == castOther.getChangedById()));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getTimeIntervalId();
		result = 37 * result + (int) this.getChangedById();
		return result;
	}

}
