package eu.city4age.dashboard.api.model;

import java.util.Date;

// default package
// Generated 24-Nov-2016 15:43:47 by Hibernate Tools 5.2.0.Beta1

/**
 * FrailtyStatusTimeline generated by hbm2java
 */
public class FrailtyStatusTimeline extends AbstractBaseEntity {

	private FrailtyStatusTimelineId frailtyStatusTimelineId;
	private TimeInterval timeInterval;
	private UserInRole userInRole;
	private UserInRole changedBy;
	private String frailtyStatus;
	private String frailtyNotice;
	private Date changed;
	private CdFrailtyStatus cdFrailtyStatus;

	public FrailtyStatusTimeline() {
	}

	
	public FrailtyStatusTimelineId getFrailtyStatusTimelineId() {
		return frailtyStatusTimelineId;
	}


	public void setFrailtyStatusTimelineId(FrailtyStatusTimelineId frailtyStatusTimelineId) {
		this.frailtyStatusTimelineId = frailtyStatusTimelineId;
	}


	public FrailtyStatusTimeline(TimeInterval timeInterval, UserInRole userInRole, UserInRole changedBy,
			String frailtyStatus) {
		this.timeInterval = timeInterval;
		this.userInRole = userInRole;
		this.changedBy = changedBy;
		this.frailtyStatus = frailtyStatus;
	}

	public FrailtyStatusTimeline(TimeInterval timeInterval, UserInRole userInRole, UserInRole changedBy,
			String frailtyStatus, String frailtyNotice) {
		this.timeInterval = timeInterval;
		this.userInRole = userInRole;
		this.changedBy = changedBy;
		this.frailtyStatus = frailtyStatus;
		this.frailtyNotice = frailtyNotice;
	}

	public TimeInterval getTimeInterval() {
		return this.timeInterval;
	}

	public void setTimeInterval(TimeInterval timeInterval) {
		this.timeInterval = timeInterval;
	}

	public UserInRole getUserInRole() {
		return this.userInRole;
	}

	public void setUserInRole(UserInRole userInRole) {
		this.userInRole = userInRole;
	}

	public UserInRole getChangedBy() {
		return changedBy;
	}


	public void setChangedBy(UserInRole changedBy) {
		this.changedBy = changedBy;
	}


	public String getFrailtyStatus() {
		return this.frailtyStatus;
	}

	public void setFrailtyStatus(String frailtyStatus) {
		this.frailtyStatus = frailtyStatus;
	}

	public String getFrailtyNotice() {
		return this.frailtyNotice;
	}

	public void setFrailtyNotice(String frailtyNotice) {
		this.frailtyNotice = frailtyNotice;
	}


	public Date getChanged() {
		return changed;
	}


	public void setChanged(Date changed) {
		this.changed = changed;
	}


	public CdFrailtyStatus getCdFrailtyStatus() {
		return cdFrailtyStatus;
	}


	public void setCdFrailtyStatus(CdFrailtyStatus cdFrailtyStatus) {
		this.cdFrailtyStatus = cdFrailtyStatus;
	}

	
	
}
