package eu.city4age.dashboard.api.model;

import java.sql.Timestamp;

/**
 * FrailtyStatusTimelineId generated by hbm2java
 */
public class FrailtyStatusTimelineId implements java.io.Serializable {

	private Long timeIntervalId;
	private Timestamp changed;
	private Long userInRoleId;
	private String frailtyStatus;

	
	public FrailtyStatusTimelineId() {
	}

	public FrailtyStatusTimelineId(Long timeIntervalId, Timestamp changed, Long userInRoleId, String frailtyStatus) {
		this.timeIntervalId = timeIntervalId;
		this.changed = changed;
		this.userInRoleId = userInRoleId;
		this.frailtyStatus = frailtyStatus;
	}

	public Long getTimeIntervalId() {
		return timeIntervalId;
	}

	public void setTimeIntervalId(Long timeIntervalId) {
		this.timeIntervalId = timeIntervalId;
	}

	public Timestamp getChanged() {
		return changed;
	}

	public void setChanged(Timestamp changed) {
		this.changed = changed;
	}

	public Long getUserInRoleId() {
		return userInRoleId;
	}

	public void setUserInRoleId(Long userInRoleId) {
		this.userInRoleId = userInRoleId;
	}

	public String getFrailtyStatus() {
		return frailtyStatus;
	}

	public void setFrailtyStatus(String frailtyStatus) {
		this.frailtyStatus = frailtyStatus;
	}
	

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FrailtyStatusTimelineId))
			return false;
		FrailtyStatusTimelineId castOther = (FrailtyStatusTimelineId) other;

		return (this.getTimeIntervalId() == castOther.getTimeIntervalId())
				&& (this.getChanged() == castOther.getChanged())
				&& (this.getUserInRoleId() == castOther.getUserInRoleId())
				&& (this.getFrailtyStatus() == castOther.getFrailtyStatus());
	}

	public int hashCode() {
	    StringBuilder builder = new StringBuilder();
	    builder.append(timeIntervalId.toString());
	    builder.append(changed.toString());
	    builder.append(userInRoleId.toString());
	    builder.append(frailtyStatus.toString());
	    return builder.toString().hashCode();
	}

}
