package eu.city4age.dashboard.api.model;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonFilter;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

/**
 * GeriatricFactorValue generated by hbm2java
 */
public class GeriatricFactorValue extends AbstractBaseEntity {

	private BigDecimal gefValue;
	
	@JsonIgnore
	private TimeInterval timeInterval;
	
	private CdDetectionVariable cdDetectionVariable;
	private UserInRole userInRole;
	private String dataSourceType;
	
	private BigDecimal derivationWeight;

	private Set<SourceEvidence> sourceEvidences = new HashSet<SourceEvidence>(0);
	
	private Set<NumericIndicatorValue> numericIndicatorValues = new HashSet<NumericIndicatorValue>(0);

	@JsonBackReference
	private Set<Assessment> assessments = new HashSet<Assessment>(0);

	public GeriatricFactorValue() {
	}

	public GeriatricFactorValue(BigDecimal gefValue, TimeInterval timeInterval, CdDetectionVariable cdDetectionVariable, UserInRole userInRole,
			String dataSourceType, Set<SourceEvidence> sourceEvidences, Set<NumericIndicatorValue> numericIndicatorValues,
			Set<Assessment> assessments) {
		this.gefValue = gefValue;
		this.timeInterval = timeInterval;
		this.cdDetectionVariable = cdDetectionVariable;
		this.userInRole = userInRole;
		this.dataSourceType = dataSourceType;
		this.sourceEvidences = sourceEvidences;
		this.numericIndicatorValues = numericIndicatorValues;
		this.assessments = assessments;
	}

	public BigDecimal getGefValue() {
		return this.gefValue;
	}

	public void setGefValue(BigDecimal gefValue) {
		this.gefValue = gefValue;
	}


	public TimeInterval getTimeInterval() {
		return timeInterval;
	}

	public void setTimeInterval(TimeInterval timeInterval) {
		this.timeInterval = timeInterval;
	}

	public CdDetectionVariable getCdDetectionVariable() {
		return cdDetectionVariable;
	}

	public void setCdDetectionVariable(CdDetectionVariable cdDetectionVariable) {
		this.cdDetectionVariable = cdDetectionVariable;
	}

	public UserInRole getUserInRole() {
		return userInRole;
	}

	public void setUserInRole(UserInRole userInRole) {
		this.userInRole = userInRole;
	}

	public String getDataSourceType() {
		return this.dataSourceType;
	}

	public void setDataSourceType(String dataSourceType) {
		this.dataSourceType = dataSourceType;
	}

	public BigDecimal getDerivationWeight() {
		return derivationWeight;
	}

	public void setDerivationWeight(BigDecimal derivationWeight) {
		this.derivationWeight = derivationWeight;
	}

	public Set<SourceEvidence> getSourceEvidences() {
		return this.sourceEvidences;
	}

	public void setSourceEvidences(Set<SourceEvidence> sourceEvidences) {
		this.sourceEvidences = sourceEvidences;
	}

	public Set<NumericIndicatorValue> getNumericIndicatorValues() {
		return numericIndicatorValues;
	}

	public void setNumericIndicatorValues(Set<NumericIndicatorValue> numericIndicatorValues) {
		this.numericIndicatorValues = numericIndicatorValues;
	}
	
	public Set<Assessment> getAssessments() {
		return assessments;
	}

	public void setAssessments(Set<Assessment> assessments) {
		this.assessments = assessments;
	}

	public void addAssessment(Assessment assessment) {
		this.assessments.add(assessment);
	}

	public CdDetectionVariable getGefTypeId() {
		return this.cdDetectionVariable;
	}


}
