package eu.city4age.dashboard.api.model;

// default package
// Generated 24-Nov-2016 15:43:47 by Hibernate Tools 5.2.0.Beta1

/**
 * InterActivityBehaviourVariation generated by hbm2java
 */
public class InterActivityBehaviourVariation extends AbstractBaseEntity {

	private Activity activityByRealActivityId;
	private Activity activityByExpectedActivityId;
	private NumericIndicatorValue numericIndicatorValue;
	private Float deviation;

	public InterActivityBehaviourVariation() {
	}

	public InterActivityBehaviourVariation(Activity activityByRealActivityId,
			Activity activityByExpectedActivityId, NumericIndicatorValue numericIndicatorValue) {
		this.activityByRealActivityId = activityByRealActivityId;
		this.activityByExpectedActivityId = activityByExpectedActivityId;
		this.numericIndicatorValue = numericIndicatorValue;
	}

	public InterActivityBehaviourVariation(Activity activityByRealActivityId,
			Activity activityByExpectedActivityId, NumericIndicatorValue numericIndicatorValue, Float deviation) {
		this.activityByRealActivityId = activityByRealActivityId;
		this.activityByExpectedActivityId = activityByExpectedActivityId;
		this.numericIndicatorValue = numericIndicatorValue;
		this.deviation = deviation;
	}

	public Activity getActivityByRealActivityId() {
		return this.activityByRealActivityId;
	}

	public void setActivityByRealActivityId(Activity activityByRealActivityId) {
		this.activityByRealActivityId = activityByRealActivityId;
	}

	public Activity getActivityByExpectedActivityId() {
		return this.activityByExpectedActivityId;
	}

	public void setActivityByExpectedActivityId(Activity activityByExpectedActivityId) {
		this.activityByExpectedActivityId = activityByExpectedActivityId;
	}

	public NumericIndicatorValue getNumericIndicatorValue() {
		return this.numericIndicatorValue;
	}

	public void setNumericIndicatorValue(NumericIndicatorValue numericIndicatorValue) {
		this.numericIndicatorValue = numericIndicatorValue;
	}

	public Float getDeviation() {
		return this.deviation;
	}

	public void setDeviation(Float deviation) {
		this.deviation = deviation;
	}

}
