package eu.city4age.dashboard.api.model;

// default package
// Generated 24-Nov-2016 15:43:47 by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * Location generated by hbm2java
 */
public class Location extends AbstractBaseEntity {

	private Pilot pilot;
	private String locationName;
	private Short indoor;
	private Set executedActions = new HashSet(0);

	public Location() {
	}

	public Location(Pilot pilot, String locationName, Short indoor, Set executedActions) {
		this.pilot = pilot;
		this.locationName = locationName;
		this.indoor = indoor;
		this.executedActions = executedActions;
	}

	public Pilot getPilot() {
		return this.pilot;
	}

	public void setPilot(Pilot pilot) {
		this.pilot = pilot;
	}

	public String getLocationName() {
		return this.locationName;
	}

	public void setLocationName(String locationName) {
		this.locationName = locationName;
	}

	public Short getIndoor() {
		return this.indoor;
	}

	public void setIndoor(Short indoor) {
		this.indoor = indoor;
	}

	public Set getExecutedActions() {
		return this.executedActions;
	}

	public void setExecutedActions(Set executedActions) {
		this.executedActions = executedActions;
	}

}
