package eu.city4age.dashboard.api.model;

// default package
// Generated 24-Nov-2016 15:43:47 by Hibernate Tools 5.2.0.Beta1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * NumericIndicatorValue generated by hbm2java
 */
public class NumericIndicatorValue extends AbstractBaseEntity {

	private CdDataSourceType cdDataSourceType;
	private CdDetectionVariable cdDetectionVariable;
	private TimeInterval timeInterval;
	private UserInRole userInRole;
	private VariationMeasureValue variationMeasureValue;
	private BigDecimal nuiValue;
	private Set interActivityBehaviourVariations = new HashSet(0);
	private Set assessedSets = new HashSet(0);

	public NumericIndicatorValue() {
	}

	public NumericIndicatorValue(CdDataSourceType cdDataSourceType, CdDetectionVariable cdDetectionVariable,
			TimeInterval timeInterval, VariationMeasureValue variationMeasureValue, BigDecimal nuiValue) {
		this.cdDataSourceType = cdDataSourceType;
		this.cdDetectionVariable = cdDetectionVariable;
		this.timeInterval = timeInterval;
		this.variationMeasureValue = variationMeasureValue;
		this.nuiValue = nuiValue;
	}

	public NumericIndicatorValue(CdDataSourceType cdDataSourceType, CdDetectionVariable cdDetectionVariable,
			TimeInterval timeInterval, UserInRole userInRole, VariationMeasureValue variationMeasureValue,
			BigDecimal nuiValue, Set interActivityBehaviourVariations, Set assessedSets, Set nuiGefs) {
		this.cdDataSourceType = cdDataSourceType;
		this.cdDetectionVariable = cdDetectionVariable;
		this.timeInterval = timeInterval;
		this.userInRole = userInRole;
		this.variationMeasureValue = variationMeasureValue;
		this.nuiValue = nuiValue;
		this.interActivityBehaviourVariations = interActivityBehaviourVariations;
		this.assessedSets = assessedSets;
	}

	public CdDataSourceType getCdDataSourceType() {
		return this.cdDataSourceType;
	}

	public void setCdDataSourceType(CdDataSourceType cdDataSourceType) {
		this.cdDataSourceType = cdDataSourceType;
	}

	public CdDetectionVariable getCdDetectionVariable() {
		return this.cdDetectionVariable;
	}

	public void setCdDetectionVariable(CdDetectionVariable cdDetectionVariable) {
		this.cdDetectionVariable = cdDetectionVariable;
	}

	public TimeInterval getTimeInterval() {
		return this.timeInterval;
	}

	public void setTimeInterval(TimeInterval timeInterval) {
		this.timeInterval = timeInterval;
	}

	public UserInRole getUserInRole() {
		return this.userInRole;
	}

	public void setUserInRole(UserInRole userInRole) {
		this.userInRole = userInRole;
	}

	public VariationMeasureValue getVariationMeasureValue() {
		return this.variationMeasureValue;
	}

	public void setVariationMeasureValue(VariationMeasureValue variationMeasureValue) {
		this.variationMeasureValue = variationMeasureValue;
	}

	public BigDecimal getNuiValue() {
		return this.nuiValue;
	}

	public void setNuiValue(BigDecimal nuiValue) {
		this.nuiValue = nuiValue;
	}

	public Set getInterActivityBehaviourVariations() {
		return this.interActivityBehaviourVariations;
	}

	public void setInterActivityBehaviourVariations(Set interActivityBehaviourVariations) {
		this.interActivityBehaviourVariations = interActivityBehaviourVariations;
	}

	public Set getAssessedSets() {
		return this.assessedSets;
	}

	public void setAssessedSets(Set assessedSets) {
		this.assessedSets = assessedSets;
	}
	
}
