package eu.city4age.dashboard.api.model;

// default package
// Generated 24-Nov-2016 15:43:47 by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * Pilot generated by hbm2java
 */
public class Pilot extends AbstractBaseEntity {

	private String name;
	private String pilotCode;
	private Double populationSize;
	private Set locations = new HashSet(0);
	private Set cdPilotDetectionVariables = new HashSet(0);

	public Pilot() {
	}

	public Pilot(String name, String pilotCode, Double populationSize, Set locations, Set cdPilotDetectionVariables) {
		this.name = name;
		this.pilotCode = pilotCode;
		this.populationSize = populationSize;
		this.locations = locations;
		this.cdPilotDetectionVariables = cdPilotDetectionVariables;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPilotCode() {
		return pilotCode;
	}

	public void setPilotCode(String pilotCode) {
		this.pilotCode = pilotCode;
	}

	public Double getPopulationSize() {
		return this.populationSize;
	}

	public void setPopulationSize(Double populationSize) {
		this.populationSize = populationSize;
	}

	public Set getLocations() {
		return this.locations;
	}

	public void setLocations(Set locations) {
		this.locations = locations;
	}

	public Set getCdPilotDetectionVariables() {
		return this.cdPilotDetectionVariables;
	}

	public void setCdPilotDetectionVariables(Set cdPilotDetectionVariables) {
		this.cdPilotDetectionVariables = cdPilotDetectionVariables;
	}

}
