package eu.city4age.dashboard.api.model;

// default package
// Generated 24-Nov-2016 15:43:47 by Hibernate Tools 5.2.0.Beta1

/**
 * SimplelocationEam generated by hbm2java
 */
public class SimplelocationEam extends AbstractBaseEntity {

	private Simplelocation simpleLocation;
	private Eam eam;

	public SimplelocationEam() {
	}

	public SimplelocationEam(Simplelocation simpleLocation, Eam eam) {
		this.simpleLocation = simpleLocation;
		this.eam = eam;
	}

	public Simplelocation getSimpleLocation() {
		return simpleLocation;
	}

	public void setSimpleLocation(Simplelocation simpleLocation) {
		this.simpleLocation = simpleLocation;
	}

	public Eam getEam() {
		return eam;
	}

	public void setEam(Eam eam) {
		this.eam = eam;
	}

}
