package eu.city4age.dashboard.api.model;

import java.io.Serializable;

// default package
// Generated 24-Nov-2016 15:43:47 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;

/**
 * SourceEvidence generated by hbm2java
 */
public class SourceEvidence implements Serializable {

	private SourceEvidenceId sourceEvidenceId;
	private GeriatricFactorValue geriatricFactorValue;
	private UserInRole userInRole;
	private String textEvidence;
	private byte[] multimediaEvidence;
	private Date uploaded;

	public SourceEvidence() {
	}

	public SourceEvidence(GeriatricFactorValue geriatricFactorValue, Date uploaded) {
		this.geriatricFactorValue = geriatricFactorValue;
		this.uploaded = uploaded;
	}

	public SourceEvidence(GeriatricFactorValue geriatricFactorValue, UserInRole userInRole,
			String textEvidence, byte[] multimediaEvidence, Date uploaded) {
		this.geriatricFactorValue = geriatricFactorValue;
		this.userInRole = userInRole;
		this.textEvidence = textEvidence;
		this.multimediaEvidence = multimediaEvidence;
		this.uploaded = uploaded;
	}
	
	

	public SourceEvidenceId getSourceEvidenceId() {
		return sourceEvidenceId;
	}

	public void setSourceEvidenceId(SourceEvidenceId sourceEvidenceId) {
		this.sourceEvidenceId = sourceEvidenceId;
	}

	public GeriatricFactorValue getGeriatricFactorValue() {
		return this.geriatricFactorValue;
	}

	public void setGeriatricFactorValue(GeriatricFactorValue geriatricFactorValue) {
		this.geriatricFactorValue = geriatricFactorValue;
	}

	public UserInRole getUserInRole() {
		return this.userInRole;
	}

	public void setUserInRole(UserInRole userInRole) {
		this.userInRole = userInRole;
	}

	public String getTextEvidence() {
		return this.textEvidence;
	}

	public void setTextEvidence(String textEvidence) {
		this.textEvidence = textEvidence;
	}

	public byte[] getMultimediaEvidence() {
		return this.multimediaEvidence;
	}

	public void setMultimediaEvidence(byte[] multimediaEvidence) {
		this.multimediaEvidence = multimediaEvidence;
	}

	public Date getUploaded() {
		return this.uploaded;
	}

	public void setUploaded(Date uploaded) {
		this.uploaded = uploaded;
	}

}
