package eu.city4age.dashboard.api.model;

import java.io.Serializable;

// default package
// Generated 24-Nov-2016 15:43:47 by Hibernate Tools 5.2.0.Beta1

/**
 * SourceEvidenceId generated by hbm2java
 */
public class SourceEvidenceId implements Serializable {

	private int geriatricFactorId;
	private int userInRoleId;

	public SourceEvidenceId() {
	}

	public SourceEvidenceId(int geriatricFactorId, int userInRoleId) {
		this.geriatricFactorId = geriatricFactorId;
		this.userInRoleId = userInRoleId;
	}

	public int getGeriatricFactorId() {
		return this.geriatricFactorId;
	}

	public void setGeriatricFactorId(int geriatricFactorId) {
		this.geriatricFactorId = geriatricFactorId;
	}

	public int getUserInRoleId() {
		return userInRoleId;
	}

	public void setUserInRoleId(int userInRoleId) {
		this.userInRoleId = userInRoleId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SourceEvidenceId))
			return false;
		SourceEvidenceId castOther = (SourceEvidenceId) other;

		return (this.getGeriatricFactorId() == castOther.getGeriatricFactorId())
				&& ((this.getUserInRoleId() == castOther.getUserInRoleId()));
	}
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getGeriatricFactorId();
		result = 37 * result + this.getUserInRoleId();
		return result;
	}

}
