package eu.city4age.dashboard.api.model;

// default package
// Generated 24-Nov-2016 15:43:47 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Startrange generated by hbm2java
 */
public class Startrange extends AbstractBaseEntity {

	private Date startHour;
	private Date endHour;
	private Set eams = new HashSet(0);

	public Startrange() {
	}

	public Startrange(Date startHour, Date endHour) {
		this.startHour = startHour;
		this.endHour = endHour;
	}

	public Startrange(Date startHour, Date endHour, Set eams) {
		this.startHour = startHour;
		this.endHour = endHour;
		this.eams = eams;
	}

	public Date getStartHour() {
		return this.startHour;
	}

	public void setStartHour(Date startHour) {
		this.startHour = startHour;
	}

	public Date getEndHour() {
		return this.endHour;
	}

	public void setEndHour(Date endHour) {
		this.endHour = endHour;
	}

	public Set getEams() {
		return this.eams;
	}

	public void setEams(Set eams) {
		this.eams = eams;
	}

}
