package eu.city4age.dashboard.api.model;

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * TimeInterval generated by hbm2java
 */
public class TimeInterval extends AbstractBaseEntity {

	@JsonIgnore
	private Timestamp intervalStart;
	
	@JsonIgnore
	private Timestamp intervalEnd;
	
	private String start;
	
	private String end;	
	
	private String typicalPeriod;
	
	private Set<Activity> activities = new HashSet<Activity>(0);
	
	private Set<NumericIndicatorValue> numericIndicatorValues = new HashSet<NumericIndicatorValue>(0);
	
	private Set<VariationMeasureValue> variationMeasureValues = new HashSet<VariationMeasureValue>(0);
	
	private Set<GeriatricFactorValue> geriatricFactorValues = new HashSet<GeriatricFactorValue>(0);

	public TimeInterval() {
	}

	public TimeInterval(Timestamp intervalStart, Timestamp intervalEnd, String typicalPeriod, Set<Activity> activities,
			Set<NumericIndicatorValue> numericIndicatorValues, Set<VariationMeasureValue> variationMeasureValues) {
		this.intervalStart = intervalStart;
		this.intervalEnd = intervalEnd;
		this.typicalPeriod = typicalPeriod;
		this.activities = activities;
		this.numericIndicatorValues = numericIndicatorValues;
		this.variationMeasureValues = variationMeasureValues;
	}


	public Timestamp getIntervalStart() {
		return intervalStart;
	}

	public void setIntervalStart(Timestamp intervalStart) {
		this.intervalStart = intervalStart;
		this.start = intervalStart.toString();
	}

	public Timestamp getIntervalEnd() {
		return intervalEnd;
	}

	public void setIntervalEnd(Timestamp intervalEnd) {
		this.intervalEnd = intervalEnd;
		this.end = intervalEnd.toString();
	}

	public String getTypicalPeriod() {
		return this.typicalPeriod;
	}

	public void setTypicalPeriod(String typicalPeriod) {
		this.typicalPeriod = typicalPeriod;
	}

	public Set<Activity> getActivities() {
		return this.activities;
	}

	public void setActivities(Set<Activity> activities) {
		this.activities = activities;
	}

	public Set<NumericIndicatorValue> getNumericIndicatorValues() {
		return this.numericIndicatorValues;
	}

	public void setNumericIndicatorValues(Set<NumericIndicatorValue> numericIndicatorValues) {
		this.numericIndicatorValues = numericIndicatorValues;
	}

	public Set<VariationMeasureValue> getVariationMeasureValues() {
		return this.variationMeasureValues;
	}

	public void setVariationMeasureValues(Set<VariationMeasureValue> variationMeasureValues) {
		this.variationMeasureValues = variationMeasureValues;
	}

	public Set<GeriatricFactorValue> getGeriatricFactorValues() {
		return geriatricFactorValues;
	}

	public void setGeriatricFactorValues(Set<GeriatricFactorValue> geriatricFactorValues) {
		this.geriatricFactorValues = geriatricFactorValues;
	}

	public String getStart() {
		return start;
	}

	public void setStart(String start) {
		this.start = start;
	}

	public String getEnd() {
		return end;
	}

	public void setEnd(String end) {
		this.end = end;
	}

}
