package eu.city4age.dashboard.api.model;

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * TimeInterval generated by hbm2java
 */
public class TimeInterval extends AbstractBaseEntity {

	private Timestamp intervalStart;
	private Timestamp intervalEnd;
	private String start;
	private String end;	
	private String typicalPeriod;
	private Set activities = new HashSet(0);
	private Set numericIndicatorValues = new HashSet(0);
	private Set variationMeasureValues = new HashSet(0);
	private Set frailtyStatusTimelines = new HashSet(0);
	
	@JsonManagedReference
	private Set<GeriatricFactorValue> geriatricFactorValues = new HashSet<GeriatricFactorValue>();

	public TimeInterval() {
	}

	public TimeInterval(Timestamp intervalStart, Timestamp intervalEnd, String typicalPeriod, Set activities,
			Set numericIndicatorValues, Set variationMeasureValues, Set frailtyStatusTimelines) {
		this.intervalStart = intervalStart;
		this.intervalEnd = intervalEnd;
		this.typicalPeriod = typicalPeriod;
		this.activities = activities;
		this.numericIndicatorValues = numericIndicatorValues;
		this.variationMeasureValues = variationMeasureValues;
		this.frailtyStatusTimelines = frailtyStatusTimelines;
	}


	public Timestamp getIntervalStart() {
		return intervalStart;
	}

	public void setIntervalStart(Timestamp intervalStart) {
		this.intervalStart = intervalStart;
		this.start = intervalStart.toString();
	}

	public Timestamp getIntervalEnd() {
		return intervalEnd;
	}

	public void setIntervalEnd(Timestamp intervalEnd) {
		this.intervalEnd = intervalEnd;
		this.end = intervalEnd.toString();
	}

	public String getTypicalPeriod() {
		return this.typicalPeriod;
	}

	public void setTypicalPeriod(String typicalPeriod) {
		this.typicalPeriod = typicalPeriod;
	}

	public Set getActivities() {
		return this.activities;
	}

	public void setActivities(Set activities) {
		this.activities = activities;
	}

	public Set getNumericIndicatorValues() {
		return this.numericIndicatorValues;
	}

	public void setNumericIndicatorValues(Set numericIndicatorValues) {
		this.numericIndicatorValues = numericIndicatorValues;
	}

	public Set getVariationMeasureValues() {
		return this.variationMeasureValues;
	}

	public void setVariationMeasureValues(Set variationMeasureValues) {
		this.variationMeasureValues = variationMeasureValues;
	}

	public Set getFrailtyStatusTimelines() {
		return this.frailtyStatusTimelines;
	}

	public void setFrailtyStatusTimelines(Set frailtyStatusTimelines) {
		this.frailtyStatusTimelines = frailtyStatusTimelines;
	}

	public Set<GeriatricFactorValue> getGeriatricFactorValues() {
		return geriatricFactorValues;
	}

	public void setGeriatricFactorValues(Set<GeriatricFactorValue> geriatricFactorValues) {
		this.geriatricFactorValues = geriatricFactorValues;
	}

	public String getStart() {
		return start;
	}

	public void setStart(String start) {
		this.start = start;
	}

	public String getEnd() {
		return end;
	}

	public void setEnd(String end) {
		this.end = end;
	}

}
