package eu.city4age.dashboard.api.model;

// default package
// Generated 24-Nov-2016 15:43:47 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;

/**
 * UserInRole generated by hbm2java
 */
public class UserInRole extends AbstractBaseEntity {

	private Integer pilotId;
	private Date validFrom;
	private Date validTo;
	private UserInSystem userInSystem;
	private Short roleId;
	private CareProfile careProfileById;


	public UserInRole() {
	}

	public UserInRole(Integer pilotId, Date validFrom, Date validTo, UserInSystem userInSystem, Short roleId,
			CareProfile careProfileById) {
		this.pilotId = pilotId;
		this.validFrom = validFrom;
		this.validTo = validTo;
		this.userInSystem = userInSystem;
		this.roleId = roleId;
		this.careProfileById = careProfileById;
	}

	public Integer getPilotId() {
		return this.pilotId;
	}

	public void setPilotId(Integer pilotId) {
		this.pilotId = pilotId;
	}

	public Date getValidFrom() {
		return this.validFrom;
	}

	public void setValidFrom(Date validFrom) {
		this.validFrom = validFrom;
	}

	public Date getValidTo() {
		return this.validTo;
	}

	public void setValidTo(Date validTo) {
		this.validTo = validTo;
	}

	public UserInSystem getUserInSystem() {
		return userInSystem;
	}

	public void setUserInSystem(UserInSystem userInSystem) {
		this.userInSystem = userInSystem;
	}

	public Short getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Short roleId) {
		this.roleId = roleId;
	}

	public CareProfile getCareProfileById() {
		return this.careProfileById;
	}

	public void setCareProfileById(CareProfile careProfileById) {
		this.careProfileById = careProfileById;
	}

}
