package eu.city4age.dashboard.api.model;

// default package
// Generated 24-Nov-2016 15:43:47 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;

/**
 * UserInSystem generated by hbm2java
 */
public class UserInSystem extends AbstractBaseEntity {

	private String username;
	private String password;
	private Date createdDate;

	public UserInSystem() {
	}

	public UserInSystem(String username, String password, Date createdDate) {
		this.username = username;
		this.password = password;
		this.createdDate = createdDate;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

}
