package eu.city4age.dashboard.api.model;

// default package
// Generated 24-Nov-2016 15:43:47 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UserInRole generated by hbm2java
 */
public class UserInRole extends AbstractBaseEntity {

	private Integer pilotId;
	private Date validFrom;
	private Date validTo;
	private Integer userInSystemId;
	private Short roleId;
	private Set activities = new HashSet(0);
	private Set sourceEvidences = new HashSet(0);
	private CareProfile careProfileById;
	private Set careProfilesForLastUpdatedBy = new HashSet(0);
	private Set numericIndicatorValues = new HashSet(0);
	private Set variationMeasureValues = new HashSet(0);
	private Set assessments = new HashSet(0);
	private Set careProfilesForCreatedBy = new HashSet(0);
	private Set crProfiles = new HashSet(0);
	private Set executedActions = new HashSet(0);
	private Set frailtyStatusTimelines = new HashSet(0);

	public UserInRole() {
	}

	public UserInRole(Integer pilotId, Date validFrom, Date validTo, Integer userInSystemId, Short roleId,
			Set activities, Set sourceEvidences, CareProfile careProfileById, Set careProfilesForLastUpdatedBy,
			Set numericIndicatorValues, Set variationMeasureValues, Set assessments, Set careProfilesForCreatedBy,
			Set crProfiles, Set executedActions, Set frailtyStatusTimelines) {
		this.pilotId = pilotId;
		this.validFrom = validFrom;
		this.validTo = validTo;
		this.userInSystemId = userInSystemId;
		this.roleId = roleId;
		this.activities = activities;
		this.sourceEvidences = sourceEvidences;
		this.careProfileById = careProfileById;
		this.careProfilesForLastUpdatedBy = careProfilesForLastUpdatedBy;
		this.numericIndicatorValues = numericIndicatorValues;
		this.variationMeasureValues = variationMeasureValues;
		this.assessments = assessments;
		this.careProfilesForCreatedBy = careProfilesForCreatedBy;
		this.crProfiles = crProfiles;
		this.executedActions = executedActions;
		this.frailtyStatusTimelines = frailtyStatusTimelines;
	}

	public Integer getPilotId() {
		return this.pilotId;
	}

	public void setPilotId(Integer pilotId) {
		this.pilotId = pilotId;
	}

	public Date getValidFrom() {
		return this.validFrom;
	}

	public void setValidFrom(Date validFrom) {
		this.validFrom = validFrom;
	}

	public Date getValidTo() {
		return this.validTo;
	}

	public void setValidTo(Date validTo) {
		this.validTo = validTo;
	}

	public Integer getUserInSystemId() {
		return this.userInSystemId;
	}

	public void setUserInSystemId(Integer userInSystemId) {
		this.userInSystemId = userInSystemId;
	}

	public Short getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Short roleId) {
		this.roleId = roleId;
	}

	public Set getActivities() {
		return this.activities;
	}

	public void setActivities(Set activities) {
		this.activities = activities;
	}

	public Set getSourceEvidences() {
		return this.sourceEvidences;
	}

	public void setSourceEvidences(Set sourceEvidences) {
		this.sourceEvidences = sourceEvidences;
	}

	public CareProfile getCareProfileById() {
		return this.careProfileById;
	}

	public void setCareProfileById(CareProfile careProfileById) {
		this.careProfileById = careProfileById;
	}

	public Set getCareProfilesForLastUpdatedBy() {
		return this.careProfilesForLastUpdatedBy;
	}

	public void setCareProfilesForLastUpdatedBy(Set careProfilesForLastUpdatedBy) {
		this.careProfilesForLastUpdatedBy = careProfilesForLastUpdatedBy;
	}

	public Set getNumericIndicatorValues() {
		return this.numericIndicatorValues;
	}

	public void setNumericIndicatorValues(Set numericIndicatorValues) {
		this.numericIndicatorValues = numericIndicatorValues;
	}

	public Set getVariationMeasureValues() {
		return this.variationMeasureValues;
	}

	public void setVariationMeasureValues(Set variationMeasureValues) {
		this.variationMeasureValues = variationMeasureValues;
	}

	public Set getAssessments() {
		return this.assessments;
	}

	public void setAssessments(Set assessments) {
		this.assessments = assessments;
	}

	public Set getCareProfilesForCreatedBy() {
		return this.careProfilesForCreatedBy;
	}

	public void setCareProfilesForCreatedBy(Set careProfilesForCreatedBy) {
		this.careProfilesForCreatedBy = careProfilesForCreatedBy;
	}

	public Set getCrProfiles() {
		return this.crProfiles;
	}

	public void setCrProfiles(Set crProfiles) {
		this.crProfiles = crProfiles;
	}

	public Set getExecutedActions() {
		return this.executedActions;
	}

	public void setExecutedActions(Set executedActions) {
		this.executedActions = executedActions;
	}

	public Set getFrailtyStatusTimelines() {
		return this.frailtyStatusTimelines;
	}

	public void setFrailtyStatusTimelines(Set frailtyStatusTimelines) {
		this.frailtyStatusTimelines = frailtyStatusTimelines;
	}

}
