package eu.city4age.dashboard.api.model;

// default package
// Generated 24-Nov-2016 15:43:47 by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * VariationMeasureValue generated by hbm2java
 */
public class VariationMeasureValue extends AbstractBaseEntity {

	private Activity activity;
	private CdDataSourceType cdDataSourceType;
	private CdDetectionVariable cdDetectionVariable;
	private TimeInterval timeInterval;
	private UserInRole userInRole;
	private Float measureValue;
	private Set numericIndicatorValues = new HashSet(0);

	public VariationMeasureValue() {
	}

	public VariationMeasureValue(CdDataSourceType cdDataSourceType, CdDetectionVariable cdDetectionVariable,
			TimeInterval timeInterval, UserInRole userInRole) {
		this.cdDataSourceType = cdDataSourceType;
		this.cdDetectionVariable = cdDetectionVariable;
		this.timeInterval = timeInterval;
		this.userInRole = userInRole;
	}

	public VariationMeasureValue(Activity activity, CdDataSourceType cdDataSourceType,
			CdDetectionVariable cdDetectionVariable, TimeInterval timeInterval, UserInRole userInRole,
			Float measureValue, Set numericIndicatorValues) {
		this.activity = activity;
		this.cdDataSourceType = cdDataSourceType;
		this.cdDetectionVariable = cdDetectionVariable;
		this.timeInterval = timeInterval;
		this.userInRole = userInRole;
		this.measureValue = measureValue;
		this.numericIndicatorValues = numericIndicatorValues;
	}

	public Activity getActivity() {
		return this.activity;
	}

	public void setActivity(Activity activity) {
		this.activity = activity;
	}

	public CdDataSourceType getCdDataSourceType() {
		return this.cdDataSourceType;
	}

	public void setCdDataSourceType(CdDataSourceType cdDataSourceType) {
		this.cdDataSourceType = cdDataSourceType;
	}

	public CdDetectionVariable getCdDetectionVariable() {
		return this.cdDetectionVariable;
	}

	public void setCdDetectionVariable(CdDetectionVariable cdDetectionVariable) {
		this.cdDetectionVariable = cdDetectionVariable;
	}

	public TimeInterval getTimeInterval() {
		return this.timeInterval;
	}

	public void setTimeInterval(TimeInterval timeInterval) {
		this.timeInterval = timeInterval;
	}

	public UserInRole getUserInRole() {
		return this.userInRole;
	}

	public void setUserInRole(UserInRole userInRole) {
		this.userInRole = userInRole;
	}

	public Float getMeasureValue() {
		return this.measureValue;
	}

	public void setMeasureValue(Float measureValue) {
		this.measureValue = measureValue;
	}

	public Set getNumericIndicatorValues() {
		return this.numericIndicatorValues;
	}

	public void setNumericIndicatorValues(Set numericIndicatorValues) {
		this.numericIndicatorValues = numericIndicatorValues;
	}

}
