DROP TABLE IF EXISTS action;
DROP TABLE IF EXISTS activity;
DROP TABLE IF EXISTS assessed_set;
DROP TABLE IF EXISTS assessment;
DROP TABLE IF EXISTS assessment_audience_role;
DROP TABLE IF EXISTS care_profile;
DROP TABLE IF EXISTS cd_data_source_type;
DROP TABLE IF EXISTS cd_detection_variable;
DROP TABLE IF EXISTS cd_detection_variable_type;
DROP TABLE IF EXISTS cd_pilot_detection_variable;
DROP TABLE IF EXISTS cd_role;
DROP TABLE IF EXISTS cd_typical_period;
DROP TABLE IF EXISTS cr_profile;
DROP TABLE IF EXISTS eam;
DROP TABLE IF EXISTS eam_startrange;
DROP TABLE IF EXISTS entity;
DROP TABLE IF EXISTS executed_action;
DROP TABLE IF EXISTS frailty_status_timeline;
DROP TABLE IF EXISTS geriatric_factor_value;
DROP TABLE IF EXISTS inter_activity_behaviour_variation;
DROP TABLE IF EXISTS location;
DROP TABLE IF EXISTS nui_gef;
DROP TABLE IF EXISTS numeric_indicator_value;
DROP TABLE IF EXISTS pilot;
DROP TABLE IF EXISTS simplelocation;
DROP TABLE IF EXISTS simplelocation_eam;
DROP TABLE IF EXISTS source_evidence;
DROP TABLE IF EXISTS startrange;
DROP TABLE IF EXISTS time_interval;
DROP TABLE IF EXISTS user_in_role;
DROP TABLE IF EXISTS user_in_system;
DROP TABLE IF EXISTS variation_measure_value;
DROP sequence IF EXISTS hibernate_sequence;
create table action (id int4 not null, action_name varchar(50), category varchar(25), primary key (id));
create table activity (id int4 not null, data_source_type varchar(3) not null, time_interval_id int8 not null, user_in_role_id int4 not null, activity_name varchar(50), primary key (id));
create table assessed_set (id int8 not null, assessment_id int4 not null, detection_variable_type varchar(3) not null, data_point_id int4 not null, primary key (id));
create table assessment (id int4 not null, author_id int4, assessment_comment varchar(255), risk_status char(1), data_validity_status char(1), created timestamp not null, updated timestamp, primary key (id));
create table assessment_audience_role (id int8 not null, assessment_id int4 not null, role_id int4 not null, assigned timestamp not null, primary key (id));
create table care_profile (user_in_role_id int4 not null, last_updated_by int4, created_by int4 not null, individual_summary varchar(255) not null, attention_status char(1), intervention_status char(1), last_intervention_date date, created timestamp not null, last_updated timestamp, primary key (user_in_role_id));
create table cd_data_source_type (data_source_type varchar(3) not null, data_source_type_description varchar(250) not null, primary key (data_source_type));
create table cd_detection_variable (id int4 not null, detection_variable_name varchar(100), detection_variable_type varchar(3), valid_from timestamp, valid_to timestamp, parent_id int2, primary key (id));
create table cd_detection_variable_type (detection_variable_type varchar(3) not null, detection_variable_type_description varchar(50), primary key (detection_variable_type));
create table cd_pilot_detection_variable (id int8 not null, detection_variable_id int4 not null, pilot_id int4 not null, detection_variable_description_formula varchar(255) not null, primary key (id));
create table cd_role (id int4 not null, role_name varchar(50), role_abbreviation varchar(3), role_description varchar(200), valid_from timestamp, valid_to timestamp, primary key (id));
create table cd_typical_period (typical_period varchar(3) not null, period_description varchar(50), typical_duration time, primary key (typical_period));
create table cr_profile (id int4 not null, user_in_role_id int4 not null, ref_height float4, ref_weight float4, ref_mean_blood_pressure numeric(5, 2), date time, birth_date date not null, gender bool not null, primary key (id));
create table eam (id int4 not null, actionid int4 not null, activityid int4 not null, duration int4, primary key (id));
create table eam_startrange (eam_id int4 not null, startrangeid int4 not null, primary key (startrangeid, eam_id));
create table entity (simplelocationid int4 not null, eamid int4 not null, primary key (simplelocationid, eamid));
create table executed_action (id int4 not null, actionid int4 not null, activityid int4, locationid int4 not null, userinroleid int4 not null, date timestamp not null, rating int4, sensor_id int4 not null, payload varchar(50) not null, extra_information varchar(255), primary key (id));
create table frailty_status_timeline (id int8 not null, time_interval_id int8 not null, changed_by int4 not null, frailty_status varchar(9) not null, frailty_notice varchar(200), primary key (id));
create table geriatric_factor_value (id int4 not null, gef_value numeric(3, 2), time_interval_id int8, gef_type_id int2, user_in_role_id int4, data_source_type varchar(3), primary key (id));
create table inter_activity_behaviour_variation (id int4 not null, real_activity_id int4 not null, expected_activity_id int4 not null, numeric_indicator_id int4 not null, deviation float4, primary key (id));
create table location (id int4 not null, pilot_id int4 not null, location_name varchar(50), indoor int2, primary key (id));
create table nui_gef (id int8 not null, gef_id int4 not null, nui_id int4 not null, primary key (id));
create table numeric_indicator_value (id int4 not null, data_source_type varchar(3) not null, nui_type_id int4 not null, time_interval_id int8 not null, user_in_role_id int4, variation_measure_id int4 not null, nui_value numeric(10, 2) not null, primary key (id));
create table pilot (id int4 not null, name varchar(50), population_size float8, primary key (id));
create table simplelocation (id int4 not null, simple_location_name varchar(50) not null unique, primary key (id));
create table simplelocation_eam (id int8 not null, eamid int4, primary key (id));
create table source_evidence (id int8 not null, geriatric_factor_id int4 not null, author_id int4, text_evidence varchar(255), multimedia_evidence bytea, uploaded timestamp not null, primary key (id));
create table startrange (id int4 not null, start_hour timestamp not null, end_hour timestamp not null, primary key (id));
create table time_interval (id int8 not null, interval_start timestamp, interval_end timestamp, typical_period varchar(3), primary key (id));
create table user_in_role (id int4 not null, pilot_id int4, valid_from timestamp, valid_to timestamp, user_in_system_id int4, role_id int2, primary key (id));
create table user_in_system (id int4 not null, username varchar(25) unique, password varchar(25), created_date timestamp, primary key (id));
create table variation_measure_value (id int4 not null, activity_id int4, data_source_type varchar(3) not null, measure_type_id int4 not null, time_interval_id int8 not null, user_in_role_id int4 not null, measure_value float4, primary key (id));
create sequence hibernate_sequence;
