package eu.city4age.dashboard.api.pojo.domain;

import java.io.Serializable;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import java.util.Date;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CdPilotDetectionVariable generated by hbm2java
 */
@Entity
@Table(name = "md_pilot_detection_variable")
public class PilotDetectionVariable implements Serializable {
	
	private static final long serialVersionUID = 7337284221184594172L;

	private PilotDetectionVariableId id;
	private DetectionVariable detectionVariableByDerivedDetectionVariableId;
	private DetectionVariable detectionVariableByDetectionVariableId;
	private Pilot pilot;
	private String derivationFunctionFormula;
	private Date validFrom;
	private Date validTo;

	public PilotDetectionVariable() {
	}

	public PilotDetectionVariable(PilotDetectionVariableId id,
			DetectionVariable detectionVariableByDetectionVariableId, Pilot pilot,
			String derivationFunctionFormula) {
		this.id = id;
		this.detectionVariableByDetectionVariableId = detectionVariableByDetectionVariableId;
		this.pilot = pilot;
		this.derivationFunctionFormula = derivationFunctionFormula;
	}

	public PilotDetectionVariable(PilotDetectionVariableId id,
			DetectionVariable detectionVariableByDerivedDetectionVariableId,
			DetectionVariable detectionVariableByDetectionVariableId, Pilot pilot,
			String derivationFunctionFormula, Date validFrom, Date validTo) {
		this.id = id;
		this.detectionVariableByDerivedDetectionVariableId = detectionVariableByDerivedDetectionVariableId;
		this.detectionVariableByDetectionVariableId = detectionVariableByDetectionVariableId;
		this.pilot = pilot;
		this.derivationFunctionFormula = derivationFunctionFormula;
		this.validFrom = validFrom;
		this.validTo = validTo;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "pilotId", column = @Column(name = "pilot_id", nullable = false)),
			@AttributeOverride(name = "detectionVariableId", column = @Column(name = "detection_variable_id", nullable = false)) })
	public PilotDetectionVariableId getId() {
		return this.id;
	}

	public void setId(PilotDetectionVariableId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "derived_detection_variable_id")
	public DetectionVariable getDetectionVariableByDerivedDetectionVariableId() {
		return this.detectionVariableByDerivedDetectionVariableId;
	}

	public void setDetectionVariableByDerivedDetectionVariableId(
			DetectionVariable detectionVariableByDerivedDetectionVariableId) {
		this.detectionVariableByDerivedDetectionVariableId = detectionVariableByDerivedDetectionVariableId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "detection_variable_id", nullable = false, insertable = false, updatable = false)
	public DetectionVariable getDetectionVariableByDetectionVariableId() {
		return this.detectionVariableByDetectionVariableId;
	}

	public void setDetectionVariableByDetectionVariableId(
			DetectionVariable detectionVariableByDetectionVariableId) {
		this.detectionVariableByDetectionVariableId = detectionVariableByDetectionVariableId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pilot_id", nullable = false, insertable = false, updatable = false)
	public Pilot getPilot() {
		return this.pilot;
	}

	public void setPilot(Pilot pilot) {
		this.pilot = pilot;
	}

	@Column(name = "derivation_function_formula", nullable = false)
	public String getDerivationFunctionFormula() {
		return this.derivationFunctionFormula;
	}

	public void setDerivationFunctionFormula(String derivationFunctionFormula) {
		this.derivationFunctionFormula = derivationFunctionFormula;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "valid_from", length = 29)
	public Date getValidFrom() {
		return this.validFrom;
	}

	public void setValidFrom(Date validFrom) {
		this.validFrom = validFrom;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "valid_to", length = 29)
	public Date getValidTo() {
		return this.validTo;
	}

	public void setValidTo(Date validTo) {
		this.validTo = validTo;
	}

}
