package eu.city4age.dashboard.api.pojo.domain;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.ColumnResult;
import javax.persistence.ConstructorResult;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SqlResultSetMapping;
import javax.persistence.SqlResultSetMappings;
import javax.persistence.Table;

import org.hibernate.annotations.NamedNativeQueries;
import org.hibernate.annotations.NamedNativeQuery;

import com.fasterxml.jackson.annotation.JsonView;

import eu.city4age.dashboard.api.pojo.dto.Nuis;
import eu.city4age.dashboard.api.pojo.json.view.View;

@SqlResultSetMappings(value = { @SqlResultSetMapping(name = "avgMapping", columns = { @ColumnResult(name = "avg") }),
		@SqlResultSetMapping(name = "stDevMapping", columns = { @ColumnResult(name = "st_dev") }),
		@SqlResultSetMapping(name = "best25PercMapping", columns = { @ColumnResult(name = "best_25_perc") }),
		@SqlResultSetMapping(name = "delta25PercAvgMapping", columns = { @ColumnResult(name = "delta_25_perc_avg") }),
		@SqlResultSetMapping(name = "nuis", classes = {
				@ConstructorResult(targetClass = Nuis.class,
			    columns = { @ColumnResult(name = "avg", type = BigDecimal.class),
			    		@ColumnResult(name = "stDev", type = BigDecimal.class),
			    		@ColumnResult(name = "std", type = BigDecimal.class),
			    		@ColumnResult(name = "best25", type = BigDecimal.class),
			    		@ColumnResult(name = "best", type = BigDecimal.class),
			    		@ColumnResult(name = "delta", type = BigDecimal.class) }) })
})
@NamedNativeQueries(value = {
		@NamedNativeQuery(name = "VariationMeasureValue.doWeightedAvg", resultSetMapping = "avgMapping", query = "SELECT AVG(vm.measure_value*dv.derivation_weight) AS avg FROM variation_measure_value AS vm INNER JOIN cd_detection_variable AS dv ON dv.id = vm.measure_type_id"),
		@NamedNativeQuery(name = "VariationMeasureValue.doWeightedStDev", resultSetMapping = "stDevMapping", query = "SELECT STDDEV(vm.measure_value*dv.derivation_weight)/AVG(vm.measure_value*dv.derivation_weight) AS st_dev FROM variation_measure_value AS vm INNER JOIN cd_detection_variable AS dv ON dv.id = vm.measure_type_id"),
		@NamedNativeQuery(name = "VariationMeasureValue.doWeightedBest25Perc", resultSetMapping = "best25PercMapping", query = "SELECT PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY vm.measure_value*dv.derivation_weight DESC)/AVG(vm.measure_value*dv.derivation_weight) AS best_25_perc FROM variation_measure_value AS vm INNER JOIN cd_detection_variable AS dv ON dv.id = vm.measure_type_id"),
		@NamedNativeQuery(name = "VariationMeasureValue.doWeightedDelta25PercAvg", resultSetMapping = "delta25PercAvgMapping", query = "SELECT (PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY vm.measure_value*dv.derivation_weight DESC)-AVG(vm.measure_value*dv.derivation_weight))/AVG(vm.measure_value*dv.derivation_weight) AS delta_25_perc_avg FROM variation_measure_value AS vm INNER JOIN cd_detection_variable AS dv ON dv.id = vm.measure_type_id"),
		@NamedNativeQuery(name = "VariationMeasureValue.doAllNui", resultSetMapping = "nuis", query = "WITH subq AS (SELECT AVG (vm.measure_value) avg, COALESCE (stddev_samp(vm.measure_value), 0) stDev, PERCENTILE_CONT (0.25) WITHIN GROUP (ORDER BY vm.measure_value DESC) best25 FROM variation_measure_value AS vm INNER JOIN time_interval AS ti ON ti. ID = vm.time_interval_id WHERE ti.interval_start >= :startOfMonth AND ti.interval_start <= :endOfMonth AND vm.user_in_role_id = :uirId AND vm.measure_type_id = :dvId) SELECT avg, stDev, (CASE WHEN avg != 0 THEN stDev / avg ELSE 0 END) std, best25, (CASE WHEN avg != 0 THEN best25 / avg ELSE 0 END) best, (CASE WHEN avg != 0 THEN (best25 - avg) / avg ELSE 0 END) delta FROM subq")
})
/**
 * VariationMeasureValue generated by hbm2java
 */
@Entity
@Table(name = "variation_measure_value")
public class VariationMeasureValue extends AbstractBaseEntity<Long> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2579000073949031381L;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "activity_id")
	private ExecutedActivity activity;
	
	@JsonView(View.VariationMeasureValueView.class)
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "measure_type_id", referencedColumnName = "id")
	private DetectionVariable detectionVariable;
	
	@JsonView(View.VariationMeasureValueView.class)
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "time_interval_id", referencedColumnName = "id")
	private TimeInterval timeInterval;
	
	
	@JsonView(View.VariationMeasureValueView.class)
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_in_role_id")
	private UserInRole userInRole;

	@JsonView(View.VariationMeasureValueView.class)
	@Column(name = "measure_value", precision = 30, scale = 10)
	private BigDecimal measureValue;

	@JsonView(View.VariationMeasureValueView.class)
	@Column(name = "extra_information", length = 1000)
	private String extraInformation;

	
	@Column(name = "data_source_type", length = 1000)
	private String dataSourceType;
	
	@OneToMany(mappedBy = "variationMeasureValue", fetch = FetchType.LAZY)
	private Set<SourceEvidence> sourceEvidence = new HashSet<SourceEvidence>();
	
	/*@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "measure_type_id", referencedColumnName = "detection_variable_id", insertable = false, updatable = false)
	private ViewPilotDetectionVariable vpdv;*/

	public VariationMeasureValue() {
	}

	public VariationMeasureValue(DetectionVariable detectionVariable, TimeInterval timeInterval,
			UserInRole userInRole) {
		this.detectionVariable = detectionVariable;
		this.timeInterval = timeInterval;
		this.userInRole = userInRole;
	}

	public VariationMeasureValue(ExecutedActivity activity, DetectionVariable detectionVariable, TimeInterval timeInterval,
			UserInRole userInRole, BigDecimal measureValue, String dataSourceType, String extraInformation) {
		this.activity = activity;
		this.detectionVariable = detectionVariable;
		this.timeInterval = timeInterval;
		this.userInRole = userInRole;
		this.measureValue = measureValue;
		this.dataSourceType = dataSourceType;
		this.extraInformation = extraInformation;
	}

	public ExecutedActivity getActivity() {
		return this.activity;
	}

	public void setActivity(ExecutedActivity activity) {
		this.activity = activity;
	}

	public DetectionVariable getDetectionVariable() {
		return this.detectionVariable;
	}

	public void setDetectionVariable(DetectionVariable detectionVariable) {
		this.detectionVariable = detectionVariable;
	}

	public TimeInterval getTimeInterval() {
		return this.timeInterval;
	}

	public void setTimeInterval(TimeInterval timeInterval) {
		this.timeInterval = timeInterval;
	}

	public UserInRole getUserInRole() {
		return this.userInRole;
	}

	public void setUserInRole(UserInRole userInRole) {
		this.userInRole = userInRole;
	}

	public BigDecimal getMeasureValue() {
		return this.measureValue;
	}

	public void setMeasureValue(BigDecimal measureValue) {
		this.measureValue = measureValue;
	}

	public String getDataSourceType() {
		return this.dataSourceType;
	}

	public void setDataSourceType(String dataSourceType) {
		this.dataSourceType = dataSourceType;
	}

	public String getExtraInformation() {
		return this.extraInformation;
	}

	public void setExtraInformation(String extraInformation) {
		this.extraInformation = extraInformation;
	}

	public Set<SourceEvidence> getSourceEvidence() {
		return sourceEvidence;
	}

	public void setSourceEvidence(Set<SourceEvidence> sourceEvidence) {
		this.sourceEvidence = sourceEvidence;
	}

	/*public ViewPilotDetectionVariable getVpdv() {
		return vpdv;
	}

	public void setVpdv(ViewPilotDetectionVariable vpdv) {
		this.vpdv = vpdv;
	}*/

}
