server:
  context-path: /C4A-dashboard
logging:
  level:
    org:
      hibernate: INFO
      springframework: INFO
      apache: INFO
      glassfish: INFO
    com:
      fasterxml: INFO
    eu:
      city4age: INFO
  config: classpath:log4j2.yml
spring:
  jersey:
    application-path: /C4A-dashboard/rest
  main:
    web-environment: true
    banner-mode: 'off'
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    generate-ddl: true
    database: POSTGRESQL
    properties:
      hibernate:
        flushMode: MANUAL
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
        cache.use_second_level_cache: false
        cache.use_query_cache: false
        order_updates: true
        order_inserts: true
        jdbc:
          batch_size: 50
          batch_versioned_data: true
      javax:
        persistence:
          sharedCache:
            mode: ALL
  datasource:
    url: jdbc:postgresql://localhost:5432/city4age?characterEncoding=utf8&useUnicode=true&currentSchema=city4age_sr
    driver-class-name: org.postgresql.Driver
    username: city4age_dba
    password: city4age_dba
springfox:
  documentation:
    swagger:
      v2:
        path: /rest/swagger.json